PROJECT_ID: facilities-910444929556
REGION_ID: europe-west2
QUEUE_ID: inspector-queue
SA_EMAIL: sa-inspector-tasks@facilities-910444929556.iam.gserviceaccount.com
HTTP_ENDPOINT: https://europe-west2-facilities-910444929556.cloudfunctions.net/bq_security_classifier_02_inspector
PUBSUB_NOTIFICATION_TOPIC: projects/facilities-910444929556/topics/dlp-job-notifications
BQ_RESULTS_DATASET: dlp
BQ_RESULTS_TABLE: output

# Optional fields. At least one should be provided among the _INCLUDE configs

# format: project.dataset.table1, project.dataset.table2, etc
TABLES_INCLUDE:
# format: project.dataset1, project.dataset2, etc
DATASETS_INCLUDE:
# format: project1, project2, etc
PROJECTS_INCLUDE: facilities-910444929556, zbooks-910444929556
DATASETS_EXCLUDE:
TABLES_EXCLUDE:

